version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
      - run: 
          name: Installing dependencies 2
          command: go get -u github.com/aws/aws-lambda-go
      - run: 
          name: Building project
          command: bash ./ci-build.ps1
      - persist_to_workspace:
          root: .
          paths:
            - .
      - run: exit 0
      - slack/status:
          mentions: 'A018EEQR020'
          success_message: '[${PROJECT_ENV_VAR}]Build success! :bb-dance::pet-bb-head::bb-begging:'
          failure_message: '[${PROJECT_ENV_VAR}]Build failed! :bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood:'

  upload_to_s3:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 cp ./main.zip s3://my-tf-lambda-bucket/crawler/main.zip
      - slack/status:
          mentions: 'A018EEQR020'
          success_message: '[${PROJECT_ENV_VAR}]Upload success! :bb-dance::pet-bb-head::bb-begging:'
          failure_message: '[${PROJECT_ENV_VAR}]Upload failed! :bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood:'

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Update lambda function code
          command: aws lambda update-function-code --function-name crawler_lambda --s3-bucket my-tf-lambda-bucket --s3-key crawler/main.zip

      - slack/status:
          mentions: 'A018EEQR020'
          success_message: '[${PROJECT_ENV_VAR}]Deploy success! :bb-dance::pet-bb-head::bb-begging:'
          failure_message: '[${PROJECT_ENV_VAR}]Deploy failed! :bb-no::bb-panggang-no-cry::bb-emo-bb-cry::bb-cry-till-flood:'

workflows:
  version: 2
  build:
    jobs:
      - build_project
          # filters:
          #     branches:
          #       ignore: /.*/
          #     tags:
          #       only: /.*/
      - upload_to_s3:
          requires:
            - build_project
          context: aws
      - deploy_project:
          requires:
            - upload_to_s3
          context: aws
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /.*/