version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    working_directory: ~/circle-ci-s3-deploy
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
      - run: 
          name: Installing dependencies 2
          command: go get -u github.com/aws/aws-lambda-go
      - run: 
          name: Building project
          command: bash ./ci-build.ps1
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync .\main.zip s3://my-tf-crawler-test-bucket/outputs --delete

workflows:
  version: 2
  build:
    jobs:
      - build_project
          # filters:
          #     branches:
          #       ignore: /.*/
          #     tags:
          #       only: /.*/

      - deploy_project:
          requires:
            - build_project
          context: aws
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /.*/